apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: {{ .Values.metadata.imageTag}}
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.metadata.replicas}}
  selector:
    matchLabels:
      app: nginx
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        tag: alpine
    spec:
      containers:
      - name: nginx
        image: {{ .Values.metadata.repoName }}:{{ .Values.metadata.imageTag }}
        imagePullPolicy: {{ .Values.metadata.imagePullPolicy }}
        name: {{ .Values.metadata.name }}
        resources:
          requests:
            memory: {{ .Values.metadata.cpuRequest }}
            cpu: {{ .Values.metadata.memoryRequest }}